version: '3'

services:
  
  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234

  mongo-express:
      image: mongo-express:0.54.0
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: api
        ME_CONFIG_MONGODB_ADMINPASSWORD: docker1234
        ME_CONFIG_MONGODB_SERVER: mongo
        
  node:
    image: node:10.16.3
    volumes:
      - "./api:/var/www"  
    ports:
      - "5000:5000"
    links:
      - mongo
    command: bash -c "cd /var/www && ./node_modules/.bin/pm2 start startup.json --name API --no-daemon"
    environment: 
      - URL_MONGO=mongodb://api:docker1234@mongo

  react:
    image: node:latest
    restart: always 
    volumes:
      - "./front:/var/www"  
    ports:
      - "3000:3000"
    stdin_open: true

    links:
      - node
      - mongo
    command: bash -c "cd /var/www && npm start"
   
